### ISSUE TITLE
Create a GitHub Action

### ISSUE THREAD

**Issue by bricelam** [msys2/msys2-ci-base#1]
I would love to see a [GitHub Action](https://help.github.com/en/articles/about-actions) for setting up MSYS2. I was able to get it working using the steps in your [azure-pipelines.yml](https://github.com/msys2/MINGW-packages/blob/master/azure-pipelines.yml), but it would be much better if I could just...

``` yml
- uses: msys2/setup-msys2@v1
  with:
    arch: x86_64
```
